version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - APP_ENV
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: pgsqldb
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_ACCESS_TOKEN_EXP_IN_SEC: ${JWT_ACCESS_TOKEN_EXP_IN_SEC}
      JWT_REFRESH_TOKEN_EXP_IN_SEC: ${JWT_REFRESH_TOKEN_EXP_IN_SEC}
      JWT_PUBLIC_KEY_BASE64: ${JWT_PUBLIC_KEY_BASE64}
      JWT_PRIVATE_KEY_BASE64: ${JWT_PRIVATE_KEY_BASE64}
      DEFAULT_ADMIN_USER_PASSWORD: ${DEFAULT_ADMIN_USER_PASSWORD}
      WOO_CONSUMER_KEY: ${WOO_CONSUMER_KEY}
      WOO_CONSUMER_SECRET: ${WOO_CONSUMER_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_TAX_ENABLED: ${STRIPE_TAX_ENABLED}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      VITE_GOOGLE_CLIENT_SECRET: ${VITE_GOOGLE_CLIENT_SECRET}
      VITE_GOOGLE_REDIRECT_URI: ${VITE_GOOGLE_REDIRECT_URI}
      GOOGLE_ACCESS_TOKEN: ${GOOGLE_ACCESS_TOKEN}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
      VITE_DEFAULT_TIMEZONE: ${VITE_DEFAULT_TIMEZONE}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      GOOGLE_BUSINESS_OWNER_EMAIL: ${GOOGLE_BUSINESS_OWNER_EMAIL}
      SLOT_RESERVATION_TIMEOUT_MINUTES: ${SLOT_RESERVATION_TIMEOUT_MINUTES:-30}
      SLOT_RESERVATION_CLEANUP_INTERVAL_MINUTES: ${SLOT_RESERVATION_CLEANUP_INTERVAL_MINUTES:-5}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      RESCHEDULE_BASE_URL: ${RESCHEDULE_BASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - pgsqldb
      - redis

  pgsqldb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - pgsqldb

volumes:
  node_modules:
  pgsqldata:
  redisdata:
